---
name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    uses: thenamespace/.github-private/.github/workflows/gcp-oidc-docker-build-push.yaml@main
    permissions:
      contents: read
      id-token: write
    with:
      project_id: prod-9427
      region: europe-west3
      workload_identity_provider: projects/397196751430/locations/global/workloadIdentityPools/github-pool/providers/github-provider
      docker_context: apps/storybook
      docker_file: apps/storybook/Dockerfile
  update-staging:
    needs: build-and-push
    uses: thenamespace/.github-private/.github/workflows/repository-dispatch.yaml@main
    secrets: inherit
