---
name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    uses: thenamespace/.github/.github/workflows/gcp-oidc-docker-build-push.yaml@main
    permissions:
      contents: read
      id-token: write
    with:
      project_id: ${{ vars.GCP_PROJECT_ID }}
      region: ${{ vars.GCP_REGION }}
      repository: uikit
    secrets:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

  update-staging:
    needs: build-and-push
    uses: thenamespace/.github/.github/workflows/gh-update-stg-image-tag.yaml@main
    secrets: inherit
